"""empty message

Revision ID: 6ae93be07b53
Revises: c67be1904b70
Create Date: 2021-06-20 02:45:47.464350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ae93be07b53'
down_revision = 'c67be1904b70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('post_body_key', 'post', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('post_body_key', 'post', ['body'])
    # ### end Alembic commands ###
